//
//     Generated by class-dump 3.5 (64 bit).
//
//     class-dump is Copyright (C) 1997-1998, 2000-2001, 2004-2013 by Steve Nygard.
//

#import "UIView.h"

@class NSTimer, TBCAdPersistentColorButton, TBCImageView, TBCTailFrameInfoItem, UILabel;

@interface TBCADVideoTailFrameView : UIView
{
    _Bool _enableCountdown;
    id <TBCADVideoTailFrameDelegate> _delegate;
    id <TBCADVideoTailFrameLoadFailureDelegate> _failureDeleagte;
    long long _buttonType;
    TBCImageView *_portraitImageView;
    UILabel *_nameLabel;
    TBCAdPersistentColorButton *_detailBtn;
    TBCTailFrameInfoItem *_tailFrameInfoItem;
    NSTimer *_countdownTimer;
    long long _currentCountdownValue;
    long long _totalCountdownValue;
    UILabel *_countdownLabel;
}

- (void).cxx_destruct;
@property(nonatomic) long long buttonType; // @synthesize buttonType=_buttonType;
@property(retain, nonatomic) UILabel *countdownLabel; // @synthesize countdownLabel=_countdownLabel;
@property(retain, nonatomic) NSTimer *countdownTimer; // @synthesize countdownTimer=_countdownTimer;
@property(nonatomic) long long currentCountdownValue; // @synthesize currentCountdownValue=_currentCountdownValue;
- (void)dealloc;
@property(nonatomic) __weak id <TBCADVideoTailFrameDelegate> delegate; // @synthesize delegate=_delegate;
@property(retain, nonatomic) TBCAdPersistentColorButton *detailBtn; // @synthesize detailBtn=_detailBtn;
@property(nonatomic) _Bool enableCountdown; // @synthesize enableCountdown=_enableCountdown;
- (void)enableCountdownWithSeconds:(unsigned long long)arg1;
@property(nonatomic) __weak id <TBCADVideoTailFrameLoadFailureDelegate> failureDeleagte; // @synthesize failureDeleagte=_failureDeleagte;
- (id)init;
- (void)initTailFrame;
- (id)initWithFrame:(struct CGRect)arg1;
- (void)initializeCountdownTimer;
- (void)invalidateCountdownTimer;
@property(retain, nonatomic) UILabel *nameLabel; // @synthesize nameLabel=_nameLabel;
- (void)onTimerFire;
- (void)pauseCountdownTimer;
@property(retain, nonatomic) TBCImageView *portraitImageView; // @synthesize portraitImageView=_portraitImageView;
- (void)reportTailFrameShow;
- (void)resetUI;
- (void)resumeCountdownTimer;
- (void)setBackgroundColor:(id)arg1;
- (void)setPersistentBackgroundColor:(id)arg1;
@property(retain, nonatomic) TBCTailFrameInfoItem *tailFrameInfoItem; // @synthesize tailFrameInfoItem=_tailFrameInfoItem;
@property(nonatomic) long long totalCountdownValue; // @synthesize totalCountdownValue=_totalCountdownValue;
- (void)showTailFrameView;
- (_Bool)tailFrameCountdownCanResume;
- (void)tailFrameViewClicked;
- (void)updateData:(id)arg1;

@end

