//
//     Generated by class-dump 3.5 (64 bit).
//
//     class-dump is Copyright (C) 1997-1998, 2000-2001, 2004-2013 by Steve Nygard.
//

#import "TBCLegoAdCard.h"

#import "TBCADVideoTailFrameDelegate.h"
#import "TBCPPPromotionMediaPlayerWidgetDelegate.h"
#import "TBCVideoViewDelegate.h"

@class NSString, TBCPPPromotionMediaPlayerWidget, UIViewController;

@interface TBCLegoVideoAdCard : TBCLegoAdCard <TBCVideoViewDelegate, TBCPPPromotionMediaPlayerWidgetDelegate, TBCADVideoTailFrameDelegate>
{
    UIViewController *_viewController;
    id <TBCLegoVideoAdCardDelegate> _delegate;
    TBCPPPromotionMediaPlayerWidget *_videoView;
}

+ (double)contentHeightWithItem:(id)arg1;
- (void).cxx_destruct;
- (void)bindPromotionItem:(id)arg1;
- (void)clickVideoView:(id)arg1;
- (void)cpvChargeForEventType:(id)arg1;
- (id)cpvEventTypeFromPauseReason:(long long)arg1;
- (void)dealloc;
@property(nonatomic) __weak id <TBCLegoVideoAdCardDelegate> delegate; // @synthesize delegate=_delegate;
- (_Bool)isVideoWebViewControllerOnTop;
- (void)layoutUIForItem:(id)arg1;
- (id)mediaItemFromAdVideoInfo;
- (long long)pageTypeFromBusinessType:(int)arg1;
- (void)promotionPlayerDidFail:(id)arg1;
- (void)promotionPlayerDidFinish:(id)arg1;
- (void)promotionPlayerDidPause:(id)arg1 reason:(long long)arg2;
- (void)promotionPlayerDidStart:(id)arg1;
@property(retain, nonatomic) TBCPPPromotionMediaPlayerWidget *videoView; // @synthesize videoView=_videoView;
@property(nonatomic) __weak UIViewController *viewController; // @synthesize viewController=_viewController;
- (void)tailFrameViewClicked:(id)arg1;
////- (void)tailFrameViewDidShow:(id)arg1;

// Remaining properties
@property(readonly, copy) NSString *debugDescription;
@property(readonly, copy) NSString *description;
@property(readonly) unsigned long long hash;
@property(readonly) Class superclass;

@end

