//
//     Generated by class-dump 3.5 (64 bit).
//
//     class-dump is Copyright (C) 1997-1998, 2000-2001, 2004-2013 by Steve Nygard.
//

#import "TBCBaseMpControlOverlayView.h"

#import "TBCADVideoTailFrameLoadFailureDelegate.h"
#import "TBCLoadingCircleDelegate.h"

@class NSString, TBCADVideoTailFrameView, TBCLoadingCircle, UIButton, UILabel, UIView;

@interface TBCPPPromotionOverlayView : TBCBaseMpControlOverlayView <TBCLoadingCircleDelegate, TBCADVideoTailFrameLoadFailureDelegate>
{
    TBCLoadingCircle *_spinningCircle;
    UIView *_securityView;
    UIButton *_playBtn;
    UIButton *_loadFailedBtn;
    UILabel *_loadFailedLabel;
    TBCADVideoTailFrameView *_videoTailFrameView;
    long long _currentStatus;
}

- (void).cxx_destruct;
@property(nonatomic) long long currentStatus; // @synthesize currentStatus=_currentStatus;
- (void)implTailFrameDelegate:(id)arg1;
- (id)initWithFrame:(struct CGRect)arg1;
@property(retain, nonatomic) UIButton *loadFailedBtn; // @synthesize loadFailedBtn=_loadFailedBtn;
@property(retain, nonatomic) UILabel *loadFailedLabel; // @synthesize loadFailedLabel=_loadFailedLabel;
- (void)loadingCircleFinishedAnimation;
- (void)onLoadFailedBtnClicked;
- (void)onPlayBtnClicked;
- (void)overlayControlLoadFailed;
- (void)overlayControlPause;
- (void)overlayControlPlay;
- (void)overlayShowWithType:(long long)arg1;
@property(retain, nonatomic) UIButton *playBtn; // @synthesize playBtn=_playBtn;
@property(retain, nonatomic) UIView *securityView; // @synthesize securityView=_securityView;
@property(retain, nonatomic) TBCLoadingCircle *spinningCircle; // @synthesize spinningCircle=_spinningCircle;
@property(retain, nonatomic) TBCADVideoTailFrameView *videoTailFrameView; // @synthesize videoTailFrameView=_videoTailFrameView;
- (void)setupConstraint;
- (void)setupSubviews;
- (void)tailFrameDataLoadFailure;
- (void)updateTailFrameItem:(id)arg1;
- (void)videoLoadFailed;
- (void)videoLoaded;
- (void)videoLoading;
- (void)videoPlayFinished;
- (void)videoPlayerPause;

// Remaining properties
@property(readonly, copy) NSString *debugDescription;
@property(readonly, copy) NSString *description;
@property(readonly) unsigned long long hash;
@property(readonly) Class superclass;

@end

